development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mepills
  pool: 5
  username: root
  password: root
  shost: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mepills
  pool: 5
  username: root
  password: root
  shost: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mepills
  pool: 5
  username: root
  password: root
  shost: localhost